INFO:root:(0 points) os.path.isfile("ex4.r") is True
INFO:root:Executed R('wc_data <- read.table(\'world_cup.data\', header=T, sep=\' \')')
INFO:root:Executed R('cfr_teams <- sapply(wc.data$team, function(team) cardFoulRatio(wc.data, team))')
INFO:root:Executed R('low_cfr_teams <- wc_data[wc_data$cfr<0.12, ]')
INFO:root:Executed R('low_cfr_rank <- rankAGD(low_cfr_teams)')
ERROR:root:Got exception on main handler
Traceback (most recent call last):
  File "../check.py", line 58, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/__init__.py", line 240, in __call__
    res = self.eval(p)
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/functions.py", line 86, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/functions.py", line 35, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in sort.int(scores, decreasing = TRUE, index.return = TRUE) : 
  'x' must be atomic

ERROR:root:Traceback (most recent call last):
  File "../check.py", line 58, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/__init__.py", line 240, in __call__
    res = self.eval(p)
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/functions.py", line 86, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/functions.py", line 35, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in sort.int(scores, decreasing = TRUE, index.return = TRUE) : 
  'x' must be atomic

Traceback (most recent call last):
  File "../check.py", line 58, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/__init__.py", line 240, in __call__
    res = self.eval(p)
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/functions.py", line 86, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/functions.py", line 35, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in sort.int(scores, decreasing = TRUE, index.return = TRUE) : 
  'x' must be atomic

INFO:root:(1 points) R('all.equal(wc.data, wc_data)')[0] is True
INFO:root:(1 points) R('all.equal(cfr.teams, cfr_teams)')[0] is True
ERROR:root:(1 points) Checking R('all.equal(low.cfr.teams, low_cfr_teams )')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Attributes: < Component “row.names”: Numeric: lengths (17, 0) differ >
ERROR:root:(1 points) Checking R('all.equal(low.cfr.rank, low_cfr_rank)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "../check.py", line 74, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/__init__.py", line 240, in __call__
    res = self.eval(p)
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/functions.py", line 86, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/functions.py", line 35, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal.factor(low.cfr.rank, low_cfr_rank) : 
  object 'low_cfr_rank' not found

ERROR:root:Traceback (most recent call last):
  File "../check.py", line 74, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/__init__.py", line 240, in __call__
    res = self.eval(p)
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/functions.py", line 86, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/functions.py", line 35, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal.factor(low.cfr.rank, low_cfr_rank) : 
  object 'low_cfr_rank' not found

Traceback (most recent call last):
  File "../check.py", line 74, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/__init__.py", line 240, in __call__
    res = self.eval(p)
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/functions.py", line 86, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/rpy2/robjects/functions.py", line 35, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal.factor(low.cfr.rank, low_cfr_rank) : 
  object 'low_cfr_rank' not found

INFO:root:(1 points) R('all.equal(-0.5, avgGoalDiff(wc_data, \'England\'), tolerance=1e-5)')[0] is True
INFO:root:(1 points) R('all.equal(0.04761905, cardFoulRatio(wc_data, \'Spain\'), tolerance=1e-5)')[0] is True
INFO:root:(2 points) R('all.equal(c(\'Uruguay\', \'Switzerland\', \'USA\'), as.character(rankAGD(wc_data[30:32, ])))')[0] is True
INFO:root:You got a 6 out of 8.
